Rentilla/Rentilla/Controllers/DemandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentilla.Models;
using Microsoft.AspNet.Identity;
using A11_RBS.CustomFilters;

namespace Rentilla.Controllers
{
    public class DemandsController : Controller
    {
        private InterchangeDBContext db = new InterchangeDBContext();
        private ApplicationDbContext adbc = new ApplicationDbContext();
        // GET: Demands
        public ActionResult Index()
        {
            foreach (var item in db.Demands)
            {
                item.UID = (from u in adbc.Users where u.Id.Contains(item.UID) select u.UserName).FirstOrDefault();
            }
            return View(db.Demands.ToList());
        }

        // GET: Demands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demand demand = db.Demands.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        [Authorize]
        // GET: Demands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Demands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Accepted,DateStart,DateEnd,UID,Titel,Description,Allowance,AllowanceDescription")] Demand demand)
        {
            demand.UID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Demands.Add(demand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(demand);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: Demands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demand demand = db.Demands.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: Demands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Accepted,DateStart,DateEnd,Titel,Description,Allowance,AllowanceDescription")] Demand demand)
        {
            demand.UID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Entry(demand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(demand);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: Demands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demand demand = db.Demands.Find(id);
            if (demand == null)
            {
                return HttpNotFound();
            }
            return View(demand);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: Demands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Demand demand = db.Demands.Find(id);
            db.Demands.Remove(demand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentilla/Rentilla/Controllers/OfferToDemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentilla.Models;
using Microsoft.AspNet.Identity;
using A11_RBS.CustomFilters;

namespace Rentilla.Controllers
{
    public class OfferToDemsController : Controller
    {
        private InterchangeDBContext db = new InterchangeDBContext();
        private ApplicationDbContext adbc = new ApplicationDbContext();

        // GET: OfferToDems
        public ActionResult Index(int? id)
        {
            
            var offersTodemands = from m in db.OffersToDemands
                         select m;
            if (id != null)
            {
                var demand = (from d in db.Demands where d.ID == id select d).FirstOrDefault();
                var uname = (from u in adbc.Users where u.Id.Contains(demand.UID) select u).FirstOrDefault();

                
                ViewBag.Username = uname.UserName;
                offersTodemands = offersTodemands.Where(s => s.DemandId == id);
                foreach (var item in offersTodemands)
                {
                    item.UID = (from u in adbc.Users where u.Id.Contains(item.UID) select u.UserName).FirstOrDefault();
                }
                ViewBag.Demand = demand;
                ViewBag.DemandId = id;
            }
            return View(offersTodemands);
            //return View(db.OffersToDemands.ToList());
        }

        // GET: OfferToDems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OfferToDem offerToDem = db.OffersToDemands.Find(id);
            if (offerToDem == null)
            {
                return HttpNotFound();
            }
            return View(offerToDem);
        }

        [Authorize]
        // GET: OfferToDems/Create
        public ActionResult Create(int? id)
        {
            ViewBag.ID = id;
            return View();
        }

        [Authorize]
        // POST: OfferToDems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Titel,Description,Allowance,AllowanceDescription")] OfferToDem offerToDem, int? id)
        {
            if (id != null)
            {
                offerToDem.DemandId = (int)id;
               
            }
            offerToDem.UID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.OffersToDemands.Add(offerToDem);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = offerToDem.DemandId });
            }

            return View(offerToDem);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: OfferToDems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OfferToDem offerToDem = db.OffersToDemands.Find(id);
            if (offerToDem == null)
            {
                return HttpNotFound();
            }
            return View(offerToDem);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: OfferToDems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titel,Description,Allowance,AllowanceDescription")] OfferToDem offerToDem)
        {
            offerToDem.UID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Entry(offerToDem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = offerToDem.DemandId });
            }
            return View(offerToDem);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: OfferToDems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OfferToDem offerToDem = db.OffersToDemands.Find(id);
            if (offerToDem == null)
            {
                return HttpNotFound();
            }
            return View(offerToDem);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: OfferToDems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OfferToDem offerToDem = db.OffersToDemands.Find(id);
            db.OffersToDemands.Remove(offerToDem);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = offerToDem.DemandId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentilla/Rentilla/Views/OfferToDems/Create.cshtml
@model Rentilla.Models.OfferToDem

@{
    ViewBag.Title = "Create";
}


<h2>Create an offer for this demand</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>You want to create an offer for this demand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.Label("Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titel, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Allowance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Allowance, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Allowance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description of the Allowance", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AllowanceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AllowanceDescription, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group row text-center">
            <div class="col-md-2 col-sm-2 col-xs-6">
                @Html.ActionLink("Back to List", "Index", new { id = ViewBag.ID}, new { @class = "btn btn-default hvr-icon-back NewsBtnDelet" })
            </div>
            <div class="col-md-2 col-sm-2 col-xs-6 col-xs-offset-0">
                <button type="submit" name="pAction" class="btn btn-primary hvr-icon-fade NewsBtnDelet" value="Create">Create</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentilla/Rentilla/Views/OfferToDems/Delete.cshtml
@model Rentilla.Models.OfferToDem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OfferToDem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allowance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allowance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllowanceDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllowanceDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rentilla/Rentilla/Views/OfferToDems/Details.cshtml
@model Rentilla.Models.OfferToDem

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OfferToDem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allowance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allowance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllowanceDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllowanceDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Rentilla/Rentilla/Views/OfferToDems/Edit.cshtml
@model Rentilla.Models.OfferToDem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OfferToDem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

      

        <div class="form-group">
            @Html.LabelFor(model => model.Titel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Allowance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Allowance, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Allowance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllowanceDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AllowanceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AllowanceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentilla/Rentilla/Views/OfferToDems/Index.cshtml
@model IEnumerable<Rentilla.Models.OfferToDem>

@{
    ViewBag.Title = "Index";
}

<h2>
    Demand n°@ViewBag.DemandId
    @if (User.IsInRole("administrator"))
    {
        @Html.ActionLink("Edit", "Edit", "Demands", new { id = ViewBag.DemandId }, null)
        @Html.ActionLink(" Delete", "Delete", "Demands", new { id = ViewBag.DemandId }, null)
    }
</h2>

<div>
<hr />
<dl class="dl-horizontal">
    <dt>
        State
    </dt>

    <dd>
        @ViewBag.Demand.Accepted
    </dd>

    <dt>
        Date Start
    </dt>

    <dd>
        @ViewBag.Demand.DateStart
    </dd>

    <dt>
        Date End
    </dt>

    <dd>
        @ViewBag.Demand.DateEnd
    </dd>

    <dt>
       Username
    </dt>

    <dd>
        @ViewBag.Username
    </dd>

    <dt>
        Title
    </dt>

    <dd>
        @ViewBag.Demand.Titel
    </dd>

    <dt>
        Description
    </dt>

    <dd>
        @ViewBag.Demand.Description
    </dd>

    <dt>
        Allowance
    </dt>

    <dd>
        @ViewBag.Demand.Allowance
    </dd>

    <dt>
       Allowance Description
    </dt>

    <dd>
       @ViewBag.Demand.AllowanceDescription
    </dd>

</dl>

</div>

<hr />
<div class="row">
    <div class="col-md-3">
        <h3>
            <a href="">Offers to this demand</a>
            @Html.ActionLink(" ", "Create", "OfferToDems", new { id = ViewBag.DemandId }, new { @class = "fa fa-plus-square-o fa-3", @title = "Create offer" })
        </h3>
    </div>
</div>
<table class="table table-bordered">
    <tr>
        <th>
            Username
        </th>
        <th>
            Title
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Allowance)
        </th>
        <th>
            Description of the allowance
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Titel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Allowance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AllowanceDescription)
        </td>
        <td>
            @if (User.IsInRole("administrator"))
                {
                @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                @Html.ActionLink(" Delete", "Delete", new { id = item.ID })
            }
        </td>
    </tr>
}

</table>