Rentilla/Rentilla/Controllers/DemandToOffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentilla.Models;
using Microsoft.AspNet.Identity;
using A11_RBS.CustomFilters;

namespace Rentilla.Controllers
{
    public class DemandToOffsController : Controller
    {
        private InterchangeDBContext db = new InterchangeDBContext();
        private ApplicationDbContext adbc = new ApplicationDbContext();
        // GET: DemandToOffs
        public ActionResult Index(int? id)
        {
           
            var demandsToOffers = from m in db.DemandsToOffers
                                  select m;
            
            if (id != null)
            {
                var offer = (from d in db.Offers where d.ID == id select d).FirstOrDefault();
                var uname = (from u in adbc.Users where u.Id.Contains(offer.UID) select u).FirstOrDefault();

                ViewBag.Offer = offer;
                ViewBag.Username = uname.UserName;
                demandsToOffers = demandsToOffers.Where(s => s.OfferId == id);
                foreach (var item in demandsToOffers)
                {
                    item.UID = (from u in adbc.Users where u.Id.Contains(item.UID) select u.UserName).FirstOrDefault();
                }
                
                ViewBag.OfferId = id;
            }
            return View(demandsToOffers);
            //return View(db.DemandsToOffers.ToList());
        }


        // GET: DemandToOffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DemandToOff demandToOff = db.DemandsToOffers.Find(id);
            if (demandToOff == null)
            {
                return HttpNotFound();
            }
            return View(demandToOff);
        }

        [Authorize]
        // GET: DemandToOffs/Create
        public ActionResult Create(int? id)
        {
            ViewBag.ID = id;
            return View();
        }

        [Authorize]
        // POST: DemandToOffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Accepted,DateStart,DateEnd,Titel,Description,Allowance,AllowanceDescription")] DemandToOff demandToOff, int? id)
        {
            if (id != null)
            {
                demandToOff.OfferId = (int)id;

            }
            demandToOff.UID = User.Identity.GetUserId();
            //demandToOff.Accepted = 0;
            if (ModelState.IsValid)
            {
                db.DemandsToOffers.Add(demandToOff);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = demandToOff.OfferId });
            }

            return View(demandToOff);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: DemandToOffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DemandToOff demandToOff = db.DemandsToOffers.Find(id);
            if (demandToOff == null)
            {
                return HttpNotFound();
            }
            return View(demandToOff);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: DemandToOffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Accepted,DateStart,DateEnd,Titel,Description,Allowance,AllowanceDescription")] DemandToOff demandToOff)
        {
            demandToOff.UID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Entry(demandToOff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = demandToOff.OfferId });
            }
            return View(demandToOff);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: DemandToOffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DemandToOff demandToOff = db.DemandsToOffers.Find(id);
            if (demandToOff == null)
            {
                return HttpNotFound();
            }
            return View(demandToOff);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: DemandToOffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DemandToOff demandToOff = db.DemandsToOffers.Find(id);
            db.DemandsToOffers.Remove(demandToOff);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = demandToOff.OfferId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentilla/Rentilla/Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Rentilla.Models;
using Microsoft.AspNet.Identity;
using A11_RBS.CustomFilters;

namespace Rentilla.Controllers
{
    public class OffersController : Controller
    {
        private InterchangeDBContext db = new InterchangeDBContext();
        private ApplicationDbContext adbc = new ApplicationDbContext();
        // GET: Offers
        public ActionResult Index()
        {
            foreach (var item in db.Offers)
            {
                item.UID = (from u in adbc.Users where u.Id.Contains(item.UID) select u.UserName).FirstOrDefault();
            }
            return View(db.Offers.ToList());
        }

        // GET: Offers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        [Authorize]
        // GET: Offers/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        // POST: Offers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Titel,Description,Allowance,AllowanceDescription")] Offer offer)
        {
            offer.UID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Offers.Add(offer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(offer);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: Offers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: Offers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titel,Description,Allowance,AllowanceDescription")] Offer offer)
        {
            offer.UID = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                db.Entry(offer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(offer);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // GET: Offers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offer offer = db.Offers.Find(id);
            if (offer == null)
            {
                return HttpNotFound();
            }
            return View(offer);
        }

        [AuthorizeAdminOrOwnerOfPost]
        [Authorize]
        // POST: Offers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Offer offer = db.Offers.Find(id);
            db.Offers.Remove(offer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Rentilla/Rentilla/Views/DemandToOffs/Create.cshtml
@model Rentilla.Models.DemandToOff

@{
    ViewBag.Title = "Create";
}

<h2>Create a demand for this offer</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>You want to create a demand for this offer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Accepted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Accepted, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.Accepted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateEnd, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @style = "width: 280px; height: 100px;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Allowance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Allowance, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Allowance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description of the Allowance", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AllowanceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AllowanceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <div class="form-group row text-center">
            <div class="col-md-2 col-sm-2 col-xs-6">
                @Html.ActionLink("Back to List", "Index", new { id = ViewBag.ID }, new { @class = "btn btn-default hvr-icon-back NewsBtnDelet" })
            </div>
            <div class="col-md-2 col-sm-2 col-xs-6 col-xs-offset-0">
                <button type="submit" name="pAction" class="btn btn-primary hvr-icon-fade NewsBtnDelet" value="Create">Create</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentilla/Rentilla/Views/DemandToOffs/Delete.cshtml
@model Rentilla.Models.DemandToOff

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DemandToOff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allowance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allowance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllowanceDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllowanceDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Rentilla/Rentilla/Views/DemandToOffs/Details.cshtml
@model Rentilla.Models.DemandToOff

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DemandToOff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allowance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allowance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllowanceDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllowanceDescription)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Rentilla/Rentilla/Views/DemandToOffs/Edit.cshtml
@model Rentilla.Models.DemandToOff

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Demand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Accepted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Accepted, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Accepted, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateEnd, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @style = "width: 280px; height: 100px;" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Allowance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Allowance, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Allowance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description of the Allowance", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AllowanceDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AllowanceDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <div class="form-group row text-center">
            <div class="col-md-2 col-sm-2 col-xs-6">
                @Html.ActionLink("Back to List", "Index/" + Model.ID, null, new { @class = "btn btn-default hvr-icon-back NewsBtnDelet" })
            </div>
            <div class="col-md-2 col-sm-2 col-xs-6 col-xs-offset-0">
                <button type="submit" name="pAction" class="btn btn-primary hvr-icon-fade NewsBtnDelet" value="Save">Save</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Rentilla/Rentilla/Views/DemandToOffs/Index.cshtml
@model IEnumerable<Rentilla.Models.DemandToOff>

@{
    ViewBag.Title = "Index";
}

<h2>Offer n°@ViewBag.OfferId
    @if (User.IsInRole("administrator"))
    {
        @Html.ActionLink("Edit", "Edit", "Offers", new { id = ViewBag.OfferId }, null)
        @Html.ActionLink(" Delete", "Delete", "Offers", new { id = ViewBag.OfferId }, null)
    }</h2>


<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Username
        </dt>

        <dd>
            @ViewBag.Username
        </dd>

        <dt>
            Title
        </dt>

        <dd>
            @ViewBag.Offer.Titel
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @ViewBag.Offer.Description
        </dd>

        <dt>
            Allowance
        </dt>

        <dd>
            @ViewBag.Offer.Allowance
        </dd>

        <dt>
            Allowance Description
        </dt>

        <dd>
            @ViewBag.Offer.AllowanceDescription
        </dd>

    </dl>

</div>
<hr />
<div class="row">
    <div class="col-md-3">
        <h3>
            <a href="">Demands for this offer</a>
            @Html.ActionLink(" ", "Create", "DemandToOffs", new { id = ViewBag.OfferId }, new { @class = "fa fa-plus-square-o fa-3", @title = "Create offer" })
        </h3>
    </div>
</div>
<table class="table table-bordered">
    <tr>
        <th>
            State
        </th>
        <th>
            Start
        </th>
        <th>
            End
        </th>
        <th>
            Username
        </th>
        <th>
            Title
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Allowance)
        </th>
        <th>
            Description of the allowance
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Accepted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEnd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Allowance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AllowanceDescription)
            </td>
            <td>
                @if (User.IsInRole("administrator"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                    @Html.ActionLink(" Delete", "Delete", new { id = item.ID })
                }
            </td>
        </tr>
    }

</table>